# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iosui' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosui

  target 'iosuiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosuiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'oryxso' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oryxso
  pod 'AFNetworking', '3.1.0'

  target 'oryxsoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
